scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['172.30.192.1:8081']
        labels:
          application: 'My Spring Boot Application'